version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - 8080:8080
    env_file:
      - ./packages/db/.env
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3000:3000
    env_file:
      - ./packages/db/.env
  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - 8081:8081
    env_file:
      - ./packages/db/.env