FROM oven/bun:1

WORKDIR /user/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backned ./apps/backned

RUN bun install
RUN apt-get update -y && apt-get install -y openssl
RUN bun run db:generate

EXPOSE 8080

CMD ["bun", "run", "start:backend"]