name: Deploy the frontend
on:
  push:
    branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.web
          build-args: |
            DATABASE_URL=${{ secrets.NEONDB_URL }}
          push: true
          tags: niharlnx/web:${{ github.sha }}

      - name: Deploy to the VM
        run: |
            echo "${{ secrets.SSH_PRIVATE_KEY_LAPTOP }}" > ~/ssh_key
            chmod 600 ~/ssh_key
            ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@65.2.144.189 -t "
              sudo docker stop web || true && \
              sudo docker rm web || true && \
              sudo docker run -d -p 3000:3000 --name web niharlnx/web:${{ github.sha }}
              sleep 10
              sudo docker ps"